
module Renv
  type load_enum = "main" | "development" | String

  class Client
    private
    @api_key:    String
    @project_id: String
    @branch:     String
    @envs:       Hash[String, String]

    def raise_code_error: (response: Net::HTTPResponse, code: String?)          -> void
    def http_get:  (path: String, headers?: Hash[String, String])               -> Net::HTTPResponse
    def http_post: (path: String, body: Object, headers?: Hash[String, String]) -> Net::HTTPResponse
    def config:    ()               -> Types::API::Config::response
    def branch:    (branch: String) -> Types::API::Branch::response

    public
    def initialize: (data: { api_key: String }) -> void
    def load: (branch: load_enum)               -> void
    def set:  (key: String, value: String)      -> bool
    def get:  (key: String)                     -> String?
    def all:  ()                                -> Hash[String, String]
  end
end
